# Site settings
permalink: /post/:title.html
paginate: 10000
paginate_path: "/page/:num"
title: Talking about craft
email: mary@maryrosecook.com
description: > # this means to ignore newlines until "baseurl:"
  People who make things talking about their craft
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://talkingaboutcraft.maryrosecook.com" # the base hostname & protocol for your site

# Build settings
gems: [jekyll-paginate, jekyll-compose]
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
